language: cpp

compiler: gcc
env:
  global:
    - COMPILER=g++-4.9

sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - valgrind
      - owfs
      - mosquitto
    
before_install:
  - sudo apt-add-repository ppa:mosquitto-dev/mosquitto-ppa -y
  - sudo apt-get update
  - sudo apt-get install libmosquitto1-dev
  - sudo apt-get install libmosquittopp1-dev

install:
  - pip install --user git+git://github.com/eddyxu/cpp-coveralls.git
  - sudo /etc/init.d/owhttpd stop
  - sudo /etc/init.d/owftpd stop
  - sudo /etc/init.d/owserver stop
  - sudo cp /home/travis/build/FragJage/MqttOwfs/owfs.conf /etc/owfs.conf
  - sudo /etc/init.d/owserver start

script:
  cat /usr/include/mosquitto.h;
  cat /usr/include/mosquittopp.h;
  cmake . -G"Unix Makefiles" -DCMAKE_CXX_COMPILER=$(which $COMPILER);
  make;
  ./test/bin/unittest;
  valgrind --error-exitcode=1 --leak-check=full ./test/bin/unittest;

after_success:
  coveralls --include src --gcov-options '\-lp' --gcov 'gcov-4.9';
